### ISSUE TITLE
Undefined property Api:$http_status

### ISSUE THREAD

**Issue by bukanriko** [chriskacerguis/codeigniter-restserver#1060]
Hi,

Please help, 
 i've tried this code.

![restcode2](https://user-images.githubusercontent.com/30143182/71608634-8a75a300-2bbd-11ea-92a9-2a2a75fa1182.PNG)

and get this error.

![resterror](https://user-images.githubusercontent.com/30143182/71608469-7ed5ac80-2bbc-11ea-858f-ea8d890ea4a5.PNG)

**Comment by abedputra** [comment]
same issue...

**Comment by LaurenceLLuo** [comment]
same here

**Comment by victormongi** [comment]
Same issue here...

**Comment by rraindy** [comment]
Up

**Comment by alfianricky09** [comment]
UP

**Comment by ChristianBruno** [comment]
Same issue here...

**Comment by ChristianBruno** [comment]
A temporary solution:

Enter the constants before defining the RestController class in the RestController.php file.


`<?php

namespace chriskacerguis\RestServer;

use Exception;
use stdClass;

defined('BASEPATH') or exit('No direct script access allowed');

/**
 * CodeIgniter Rest Controller
 * A fully RESTful server implementation for CodeIgniter using one library, one config file and one controller.
 *
 * @link            https://github.com/chriskacerguis/ci-restserver
 *
 * @version         4.0.0
 */

const HTTP_OK = 200;
const HTTP_CREATED = 201;
const HTTP_NOT_MODIFIED = 304;
const HTTP_BAD_REQUEST = 400;
const HTTP_UNAUTHORIZED = 401;
const HTTP_FORBIDDEN = 403;
const HTTP_NOT_FOUND = 404;
const HTTP_NOT_ACCEPTABLE = 406;
const HTTP_INTERNAL_ERROR = 500;

class RestController extends \CI_Controller
{
...
`

**Comment by adjie-code** [comment]
1. cut folder 'vendor' to application
2. open folder aplication/config/config.php 
3. find 

$config['composer_autoload'] = TRUE;

4. set TRUE composer_autoload

**Comment by fewlme** [comment]
Up

**Comment by fewlme** [comment]
Made it work : make sure you have create one controller Api.php (and not a folder /api with mutilple controller in there)

**Comment by antiartificial** [comment]
If you're encountering issues verify that the appropriate routes are setup. WRT to the Api.php controller above try something along the lines of:

$route['api/v1/users/id/(:num)'] = 'api/users/id/$1';
$route['api/v1/users'] = 'api/users';

**Comment by bccaldas** [comment]
I had the same error with `$this->http_status['METHOD_NOT_ALLOWED']` and fixed it using a solution similar to @ChristianBruno . 
I created the constant for it with the value 405.

Also due to version problems, I changed from 'const' to 'define()' and moved it above the class name.

`<?php

namespace chriskacerguis\RestServer;

use Exception;
use stdClass;

defined('BASEPATH') or exit('No direct script access allowed');

/**
 * Common HTTP status codes and their respective description.
 *
 * @link http://www.restapitutorial.com/httpstatuscodes.html
 */
define('HTTP_OK', 200);
define('HTTP_CREATED', 201);
define('HTTP_NOT_MODIFIED', 304);
define('HTTP_BAD_REQUEST', 400);
define('HTTP_UNAUTHORIZED', 401);
define('HTTP_FORBIDDEN', 403);
define('HTTP_NOT_FOUND', 404);
define('METHOD_NOT_ALLOWED', 405);
define('HTTP_NOT_ACCEPTABLE', 406);
define('HTTP_INTERNAL_ERROR', 500);

/**
 * CodeIgniter Rest Controller
 * A fully RESTful server implementation for CodeIgniter using one library, one config file and one controller.
 *
 * @link            https://github.com/chriskacerguis/ci-restserver
 *
 * @version         4.0.0
 */
class RestController extends \CI_Controller
{}`

Replaces calls from $this->http_status['METHOD_NOT_ALLOWED'] to METHOD_NOT_ALLOWED

`$this->response(
    [
        $this->config->item('rest_status_field_name')  => false,
        $this->config->item('rest_message_field_name') => $this->lang->line('text_rest_unknown_method'),
     ], METHOD_NOT_ALLOWED
);`

**Comment by pedr0vict0r** [comment]
Same error, i just inserted where is call a variable of type `const`, the tag `self ::` in front.

Example: 
line 659 => `$http_code > 0 || $http_code = HTTP_OK;`
replace to:
line 659 => `$http_code > 0 || $http_code = self::HTTP_OK;`

The solution of @bccaldas worked for me too, but i used the solution above.

**Comment by boyolaliweb** [comment]
bismillaahi, alhamdulillahi.

i'm using CI 3.1.11 and latest codeigniter-restserver v 4.0.0. i tried @pedr0vict0r solutions, its worked best for me.

i thank you :+1

**Comment by vietqmax** [comment]
1. Created: const HTTP_METHOD_NOT_ALLOWED = 405.
2. Find $this->http_status['METHOD_NOT_ALLOWED'] replace to: self::METHOD_NOT_ALLOWED.
3. Find $this->http_status['UNAUTHORIZED'] replace to: self::HTTP_UNAUTHORIZED.
4. Like @pedr0vict0r, insert where is call a variable of type const, the tag self:: in front.
Example:
line 659 => $http_code > 0 || $http_code = HTTP_OK;
replace to:
line 659 => $http_code > 0 || $http_code = self::HTTP_OK;

**Enjoy!**

**Comment by pedr0vict0r** [comment]
This issue was fixed in the master branch, but a new release tag has not yet been made available to the composer, the last one was `3.1.1`

![Screenshot_20200326_121336](https://user-images.githubusercontent.com/17133455/77662978-4b0be800-6f5b-11ea-99c5-4626dc6be16d.png)

but in composer repository (**[packagist](https://packagist.org/packages/chriskacerguis/codeigniter-restserver)**) i found the version `dev-master`

![Screenshot_20200326_122452](https://user-images.githubusercontent.com/17133455/77664428-05e8b580-6f5d-11ea-9cda-7e06e1105061.png)

so we can change:
`"chriskacerguis/codeigniter-restserver": "^3.1"`
to:
`"chriskacerguis/codeigniter-restserver": "dev-master"`
in `composer.json`  and run `composer update` to use de lasted version.

@chriskacerguis

**Comment by momon** [comment]
> This issue was fixed in the `master` branch, but a new release not available to the composer, the last one was `3.1.1`
> 
> ![Screenshot_20200326_121336](https://user-images.githubusercontent.com/17133455/77662978-4b0be800-6f5b-11ea-99c5-4626dc6be16d.png)
> 
> but in composer repository (**[packagist](https://packagist.org/packages/chriskacerguis/codeigniter-restserver)**) i found the version `dev-master`
> 
> ![Screenshot_20200326_122452](https://user-images.githubusercontent.com/17133455/77664428-05e8b580-6f5d-11ea-9cda-7e06e1105061.png)
> 
> so we can change:
> `"chriskacerguis/codeigniter-restserver": "^3.1"`
> to:
> `"chriskacerguis/codeigniter-restserver": "dev-master"`
> in `composer.json` and run `composer update` to use de lasted version.
> 
> **ps.: It's a temporary solution , the right is use release versions on your project.**
> 
> @chriskacerguis

Thank you for this.  Was able to solve the issue by changing composer as suggested.  Hopefully when the new version is released we can just switch to the regular version instead.

**Comment by omarmatijas** [comment]
I think that file contents in master branch, isn't fixing all errors. 
Still using _->http_status_ on lines  547,1718,1803,1823,1848,1883 
And not using _self::_ for contants on lines 626,664

So constant must be defined (_const HTTP_METHOD_NOT_ALLOWED = 405;_), _->http_status_ must be removed, and all reference to constants must have _self::_

**Comment by daniloritarossi** [comment]
Hi,
respect for this hard work, I tried to install via composer V 3.1,1 and then dev-master but the problem is the same described here and apparently is not resolved. So strange.

**Comment by daniloritarossi** [comment]
Strange I've cloned the project and strangely the code is different, as described there are errors at line 547 METHOD_NOT_ALLOWED costant not exists, same problem at line 1718, 1884, 1849, 1824,1804 and more ...with UNAUTHORIZED constant changed like `self::HTTP_UNAUTHORIZED` I createad a branch and modified it I'll try to push it on the server and I hope that solve something.

**Comment by gustavojg** [comment]
> Strange I've cloned the project and strangely the code is different, as described there are errors at line 547 METHOD_NOT_ALLOWED costant not exists, same problem at line 1718, 1884, 1849, 1824,1804 and more ...with UNAUTHORIZED constant changed like `self::HTTP_UNAUTHORIZED` I createad a branch and modified it. I tried to push it on the server and contribute for issue resolution but apparently I can't for the permission or/and not for this association. I try to put the file class here hope that someone can see the file and see it for solve problems.
> [RestController.zip](https://github.com/chriskacerguis/codeigniter-restserver/files/4524959/RestController.zip)

Thanks @daniloritarossi your version worked!!

**Comment by hsabino** [comment]
> Strange I've cloned the project and strangely the code is different, as described there are errors at line 547 METHOD_NOT_ALLOWED costant not exists, same problem at line 1718, 1884, 1849, 1824,1804 and more ...with UNAUTHORIZED constant changed like `self::HTTP_UNAUTHORIZED` I createad a branch and modified it. I tried to push it on the server and contribute for issue resolution but apparently I can't for the permission or/and not for this association. I try to put the file class here hope that someone can see the file and see it for solve problems.
> [RestController.zip](https://github.com/chriskacerguis/codeigniter-restserver/files/4524959/RestController.zip)

Yes, It works!!!

**Comment by mdaltaf-tech** [comment]
> Strange I've cloned the project and strangely the code is different, as described there are errors at line 547 METHOD_NOT_ALLOWED costant not exists, same problem at line 1718, 1884, 1849, 1824,1804 and more ...with UNAUTHORIZED constant changed like `self::HTTP_UNAUTHORIZED` I createad a branch and modified it. I tried to push it on the server and contribute for issue resolution but apparently I can't for the permission or/and not for this association. I try to put the file class here hope that someone can see the file and see it for solve problems.
> [RestController.zip](https://github.com/chriskacerguis/codeigniter-restserver/files/4524959/RestController.zip)

Thanks. It worked :)

**Comment by daniloritarossi** [comment]
I tried to ask a merge request #1093 FIX:: costants in a Class with all changes that solve the problems :-)  
I hope that this is included !

DR

**Comment by alifbint** [comment]
Hi i'm solving this problem with add

`/**`
`     * @var Http Status Code`
`     */`
`    private $http_status = [`
`            'METHOD_NOT_ALLOWED' => 405,`
`            'UNAUTHORIZED' => 401`
`        ];`

After line 227 from file [RestController.php](https://github.com/chriskacerguis/codeigniter-restserver/blob/master/src/RestController.php)

**Comment by MisterDuval** [comment]
use "chriskacerguis/codeigniter-restserver": "dev-master" 
in your composer.json file, as this is fixed on master branche

**Comment by momon** [comment]
> This issue was fixed in the `master` branch, but a new release not available to the composer, the last one was `3.1.1`
> 
> ![Screenshot_20200326_121336](https://user-images.githubusercontent.com/17133455/77662978-4b0be800-6f5b-11ea-99c5-4626dc6be16d.png)
> 
> but in composer repository (**[packagist](https://packagist.org/packages/chriskacerguis/codeigniter-restserver)**) i found the version `dev-master`
> 
> ![Screenshot_20200326_122452](https://user-images.githubusercontent.com/17133455/77664428-05e8b580-6f5d-11ea-9cda-7e06e1105061.png)
> 
> so we can change:
> `"chriskacerguis/codeigniter-restserver": "^3.1"`
> to:
> `"chriskacerguis/codeigniter-restserver": "dev-master"`
> in `composer.json` and run `composer update` to use de lasted version.
> 
> **ps.: It's a temporary solution , the right is use release versions on your project.**
> 
> @chriskacerguis

I went down this road a while back and now I just realized it has a very serious problem (it may not affect anyone).

If you are using different configs per environment, I just realized the rest config file isn't being loaded from a specific environment (as it does with the regular version).  So I found out (the hard way) that my API was pretty much wide open (didn't require authentication since it wasn't loading a config file).

As soon as I copied over my environment specific config file to the config root folder, then it started working correctly.  So I am pretty sure this is something in the dev version where it is only looking for that file in the config root and not pulling from environment specific files as usual.

So I strongly advise to anyone using this fix to double check and make sure your API isn't widely open.

**Comment by daniloritarossi** [comment]
Hi @momon ok, I confirm the problem, the version 3.1.1 doesn't work but branch dev-master work correctly. 
Using dev-master branch mean break the next release beacause we haven't the track of the new upgrade/update (es. 3.1.1 next 3.1.2 and next 3.2.0......)  I hope that @chriskacerguis  solve the problem about it and put on git dev-master with correct version (maybe 3.2.0)
