### ISSUE TITLE
session rest_auth should return 401 directly

### ISSUE THREAD

**Issue by ppc52776** [chriskacerguis/codeigniter-restserver#783]
When using rest_auth=session, REST_Server doesn't stop the execution but return back to user function.
For example:

```
class Api extends REST_Controller {
public function user_get() {
   $this->response([...]);
}
```

We will get the response in user_get instead of 401 unauthorized.
If I remove $this->response in user_get, we can got default 401 unauthorized.

**Comment by ppc52776** [comment]
API_KEY has the same problem.
We will get the response in user_get instead of 403 forbidden.
If I remove $this->response in user_get, we can got default {"error":"Invalid API key"} &  403 forbidden.

**Comment by kalimerre** [comment]
This commit should fix the issue (at least it did for me)
https://github.com/chriskacerguis/codeigniter-restserver/commit/54b2b9cf0698811f9fdf3a1f833f94295ef7a955

**Comment by chriskacerguis** [comment]
See here https://github.com/chriskacerguis/codeigniter-restserver/issues/790

Closing this, please reopen if you are still having the issues.

**Comment by ppc52776** [comment]
is the commit:54b2b9c merged into master or develop branch?

**Comment by kalimerre** [comment]
The commit is revert with #790 so it works with the old method

**Comment by ppc52776** [comment]
Hi @kalimerre , 
I don't understand what #790 means. 
Does  #790 roll back to previous working commit?
I have check out the master and develop branch, but the auth problem still exist.

**Comment by kalimerre** [comment]
Hey

Indeed the actual version is a roll back from December 2016 so you need to update the whole library to get back to the working functions. 

I roll back my file, made some changes and it works for me
Maybe you can attach your library file you are using actually to see if it's the good one or not ?
